version: '3'
services:
    signal:
      container_name: signal-dev
      image: signal-img
      build: .
      env_file:
        - env/.env
      networks:
        - signal-network
      ports:
        - '${APP_HOST_PORT:-8000}:8000'
      volumes:
        - './app:/usr/local/src/app'
        - './env/etc:/usr/local/etc'
    redis:
      container_name: signal-redis
      image: 'redis:${REDIS_TAG:-5}'
      networks:
         - signal-network
      ports:
        - "6379:6379"
networks:
  signal-network:
    name: signal-network
