version: '3'
services:
    signal:
      container_name: signal-dev
      image: signal-img
      build:
        context: ../
        dockerfile: ./dev/Dockerfile
      env_file:
        - .env
      networks:
        - signal-network
      ports:
        - "8000:8000"
      volumes:
        - '../app:/usr/src/host_app'
      working_dir: /usr/src/host_app
    redis:
      container_name: signal-redis
      image: redis:5.0-alpine3.9
      networks:
         - signal-network
      ports:
        - "6379:6379"
networks:
  signal-network:
    name: signal-network
